export const categories = [
  { id: "1", name: "Education" },
  { id: "2", name: "Entertainment" },
  { id: "3", name: "Groceries" },
  { id: "4", name: "Health" },
  { id: "5", name: "Insurance" },
  { id: "6", name: "Investment" },
  { id: "7", name: "Miscellaneous" },
  { id: "8", name: "Rent" },
  { id: "9", name: "Restaurants" },
  { id: "10", name: "Salary" },
  { id: "11", name: "Savings" },
  { id: "12", name: "Transportation" },
  { id: "13", name: "Utilities" },
];
