export const categories = [
  { id: "1", name: "Education", icon: "/icons/education.svg" },
  { id: "2", name: "Entertainment", icon: "/icons/entertainment.svg" },
  { id: "3", name: "Groceries", icon: "/icons/groceries.svg" },
  { id: "4", name: "Health", icon: "/icons/health.svg" },
  { id: "5", name: "Insurance", icon: "/icons/insurance.svg" },
  { id: "6", name: "Investment", icon: "/icons/investment.svg" },
  { id: "7", name: "Miscellaneous", icon: "/icons/miscellaneous.svg" },
  { id: "8", name: "Rent", icon: "/icons/rent.svg" },
  { id: "9", name: "Restaurants", icon: "/icons/restaurants.svg" },
  { id: "10", name: "Salary", icon: "/icons/salary.svg" },
  { id: "11", name: "Savings", icon: "/icons/savings.svg" },
  { id: "12", name: "Transportation", icon: "/icons/transportation.svg" },
  { id: "13", name: "Utilities", icon: "/icons/utilities.svg" },
];
