export const transactions = [
  {
    id: "1",
    name: "Edeka Purchase",
    amount: 50.75,
    category: "Groceries",
    type: "expense",
    date: "2024-10-04",
  },
  {
    id: "2",
    name: "Rent October",
    amount: 1200.0,
    category: "Rent",
    type: "expense",
    date: "2024-10-03",
  },
  {
    id: "3",
    name: "Salary October",
    amount: 1500.0,
    category: "Salary",
    type: "income",
    date: "2024-07-03",
  },
  {
    id: "4",
    name: "Insurance Premium",
    amount: 200.5,
    category: "Insurance",
    type: "expense",
    date: "2024-07-04",
  },
  {
    id: "5",
    name: "Movie Night",
    amount: 75.25,
    category: "Entertainment",
    type: "expense",
    date: "2024-07-05",
  },
  {
    id: "6",
    name: "Dinner Aroydee",
    amount: 60.0,
    category: "Restaurants",
    type: "expense",
    date: "2024-07-06",
  },
  {
    id: "7",
    name: "Investment Return",
    amount: 500.0,
    category: "Investment",
    type: "income",
    date: "2024-07-07",
  },
  {
    id: "8",
    name: "Deutschlandticket",
    amount: 30.0,
    category: "Transportation",
    type: "expense",
    date: "2024-07-08",
  },
  {
    id: "9",
    name: "neuefische Payment",
    amount: 100.0,
    category: "Education",
    type: "expense",
    date: "2024-07-09",
  },
  {
    id: "10",
    name: "Savings Deposit",
    amount: 200.0,
    category: "Savings",
    type: "income",
    date: "2024-07-10",
  },
];
